--- Makefile	2005-08-18 16:47:46.776333136 +0200
+++ Makefile	2005-08-18 17:17:04.720085064 +0200
@@ -86,6 +86,7 @@
 AMD_HOME    = $(YPSRCDIR)/amd.home
 AUTO_MASTER = $(YPSRCDIR)/auto.master
 AUTO_HOME   = $(YPSRCDIR)/auto.home
+AUTO_HPC    = $(YPSRCDIR)/auto.hpc
 AUTO_LOCAL  = $(YPSRCDIR)/auto.local
 TIMEZONE    = $(YPSRCDIR)/timezone
 LOCALE      = $(YPSRCDIR)/locale
@@ -104,9 +105,9 @@
 
 #all:  passwd group hosts rpc services netid protocols netgrp mail \
 #	shadow publickey # networks ethers bootparams printcap \
-	# amd.home auto.master auto.home auto.local passwd.adjunct \
+	# amd.home auto.master auto.home auto.hpc auto.local passwd.adjunct \
 	# timezone locale netmasks
-all: passwd group rpc services netid
+all: auto.home auto.hpc auto.master group hosts netid passwd rpc services
 
 
 ########################################################################
@@ -438,6 +439,13 @@
 	-@$(NOPUSH) || $(YPPUSH) -d $(DOMAIN) $@
 
 
+auto.hpc: $(AUTO_HPC) $(YPDIR)/Makefile
+	@echo "Updating $@..."
+	-@sed -e "/^#/d" -e s/#.*$$// $(AUTO_HPC) | $(DBLOAD) \
+		-i $(AUTO_HPC) -o $(YPMAPDIR)/$@ - $@
+	-@$(NOPUSH) || $(YPPUSH) -d $(DOMAIN) $@
+
+
 auto.local: $(AUTO_LOCAL) $(YPDIR)/Makefile
 	@echo "Updating $@..."
 	-@sed -e "/^#/d" -e s/#.*$$// $(AUTO_LOCAL) | $(DBLOAD) \
